autopkg/n8felton-recipes

ApplePrinterDrivers/AppleGutenprintPrinterDrivers.download.recipe
https://support.apple.com/kb/DL911?locale=en_US
=> Fixed article number

ApplePrinterDrivers/AppleBrotherPrinterDrivers.download.recipe, ApplePrinterDrivers/AppleCanonInkjetPrinterDrivers.download.recipe, ApplePrinterDrivers/AppleCanonLaserPrinterDrivers.download.recipe, ApplePrinterDrivers/AppleEpsonPrinterDrivers.download.recipe, ApplePrinterDrivers/AppleFujiXeroxPrinterDrivers.download.recipe, ApplePrinterDrivers/AppleGestetnerPrinterDrivers.download.recipe, ApplePrinterDrivers/AppleGutenprintPrinterDrivers.download.recipe, ApplePrinterDrivers/AppleHPPrinterDrivers.download.recipe, ApplePrinterDrivers/AppleInfoPrintPrinterDrivers.download.recipe, ApplePrinterDrivers/AppleInfotecPrinterDrivers.download.recipe, ApplePrinterDrivers/AppleLanierPrinterDrivers.download.recipe, ApplePrinterDrivers/AppleLexmarkPrinterDrivers.download.recipe, ApplePrinterDrivers/AppleNRGPrinterDrivers.download.recipe, ApplePrinterDrivers/AppleRicohPrinterDrivers.download.recipe, ApplePrinterDrivers/AppleSamsungPrinterDrivers.download.recipe, ApplePrinterDrivers/AppleSavinPrinterDrivers.download.recipe, ApplePrinterDrivers/AppleXeroxPrinterDrivers.download.recipe
Tested and validated each one.
=> Add CodeSignatureVerifier to ApplePrinterDrivers

ApplePrinterDrivers/AppleBrotherPrinterDrivers.download.recipe
Brother Drivers had an update to V 4.0. New article number added.
=> Fixed Brother Driver article number

Aladin/Aladin.munki.recipe, AppleJava/AppleJava6.munki.recipe, ApplePrinterDrivers/AppleBrotherPrinterDrivers.munki.recipe, ApplePrinterDrivers/AppleCanonInkjetPrinterDrivers.munki.recipe, ApplePrinterDrivers/AppleCanonLaserPrinterDrivers.munki.recipe, ApplePrinterDrivers/AppleEpsonPrinterDrivers.munki.recipe, ApplePrinterDrivers/AppleFujiXeroxPrinterDrivers.munki.recipe, ApplePrinterDrivers/AppleGestetnerPrinterDrivers.munki.recipe, ApplePrinterDrivers/AppleGutenprintPrinterDrivers.munki.recipe, ApplePrinterDrivers/AppleHPPrinterDrivers.munki.recipe, ApplePrinterDrivers/AppleInfoPrintPrinterDrivers.munki.recipe, ApplePrinterDrivers/AppleInfotecPrinterDrivers.munki.recipe, ApplePrinterDrivers/AppleLanierPrinterDrivers.munki.recipe, ApplePrinterDrivers/AppleLexmarkPrinterDrivers.munki.recipe, ApplePrinterDrivers/AppleNRGPrinterDrivers.munki.recipe, ApplePrinterDrivers/AppleRicohPrinterDrivers.munki.recipe, ApplePrinterDrivers/AppleSamsungPrinterDrivers.munki.recipe, ApplePrinterDrivers/AppleSavinPrinterDrivers.munki.recipe, ApplePrinterDrivers/AppleXeroxPrinterDrivers.munki.recipe, AstroImageJ/AstroImageJ.munki.recipe, BlueJ/BlueJ.munki.recipe, Geneious/Geneious.munki.recipe, Mozilla/FirefoxDeveloperEdition.munki.recipe, PAUP/PAUP.munki.recipe
=> Add MUNKI_CATEGORY as a variable for all Munki recipes

VisualParadigm/VisualParadigmCE.download.recipe, VisualParadigm/VisualParadigmCE.munki.recipe
Yeah, it's a paradigm shift!
```
$ autopkg run VisualParadigmCE.munki
Processing VisualParadigmCE.munki...
WARNING: VisualParadigmCE.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
The following new items were imported into Munki:
Name              Version  Catalogs  Pkginfo Path                                       Pkg Repo Path                                    
----              -------  --------  ------------                                       -------------                                    
VisualParadigmCE  13.2     testing   apps/VisualParadigmCE/VisualParadigmCE-13.2.plist  apps/VisualParadigmCE/VisualParadigmCE-13.2.dmg  
The following new items were downloaded:
Download Path …
```
=> Add recipe for Visual Paradigm CE

CodonCode/CodonCodeAligner.download.recipe, CodonCode/CodonCodeAligner.munki.recipe
```
$ autopkg run CodonCodeAligner.munki -v
Processing CodonCodeAligner.munki...
WARNING: CodonCodeAligner.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher: Found matching text (match): http://www.mediafire.com/download/9jmvw846m3xnm6y/Aligner_Installer.dmg
URLDownloader
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.munki.CodonCodeAligner/downloads/CodonCode Aligner.dmg
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.munki.CodonCodeAligner/downloads/CodonCode Aligner.dmg
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "CodonCode Aligner.pkg": …
```
=> Add recipe for CodonCode Aligner

AppleJava/AppleJava6.install.recipe
just doing some packer builds and autopkg installers make it easy :)
=> install for AppleJava6 download

Chimera/Chimera.download.recipe, Chimera/Chimera.munki.recipe
```
$ autopkg run Chimera.munki -v
Processing Chimera.munki...
WARNING: Chimera.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher: Found matching text (version): 1.11
URLTextSearcher: Found matching text (match): chimera-1.11-mac64.dmg
URLTextSearcher: Found matching text (file): chimera-1.11-mac64.dmg
URLTextSearcher: Found matching text (match): cgi-bin/secure/chimera-get.py?ident=B5j2BsfqowLHfKujkUa1D9LZc3CpF9Cr6P%2B%2BTV7MFMfi&file=mac64%2Fchimera-1.11-mac64.dmg&choice=Notified
URLDownloader
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.munki.Chimera/downloads/Chimera.dmg
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image …
```
=> Add recipes for Chimera

Yubico/yubioath-desktop.download.recipe, Yubico/yubioath-desktop.munki.recipe
```
$ autopkg run yubioath-desktop.munki.recipe -v
Processing yubioath-desktop.munki.recipe...
WARNING: yubioath-desktop.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider: Matched regex '.*pkg$' among asset(s): yubioath-desktop-4.1.2-mac.pkg, yubioath-desktop-4.1.2-mac.pkg.sig, yubioath-desktop-4.1.2-win.exe, yubioath-desktop-4.1.2-win.exe.sig, yubioath-desktop-4.1.2.tar.gz, yubioath-desktop-4.1.2.tar.gz.sig
GitHubReleasesInfoProvider: Selected asset 'yubioath-desktop-4.1.2-mac.pkg' from release 'yubioath-desktop-4.1.2'
URLDownloader
URLDownloader: Storing new Last-Modified header: Fri, 26 May 2017 04:26:52 GMT
URLDownloader: Storing new ETag header: "a8022c220a59b3c14f3d0e74313ff2d6" …
```
=> [Yubico] Add yubioath-desktop download and munki recipes

CodonCode/CodonCodeAligner.download.recipe
Code signature changed. 
```
CodeSignatureVerifier: Expected: Developer ID Installer: CodonCode Corporation -> Developer ID Certification Authority -> Apple Root CA
CodeSignatureVerifier: Found:    Developer ID Installer: CodonCode Corporation (SXRQ7NHBVM) -> Developer ID Certification Authority -> Apple Root CA
```
Works now:
```
$ autopkg run CodonCodeAligner.download.recipe -v
Processing CodonCodeAligner.download.recipe...
WARNING: CodonCodeAligner.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher: Found matching text (match): http://www.mediafire.com/file/jpzd8n61srfallc/Aligner_Installer.dmg
URLDownloader
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.download.CodonCode …
```
=> [CodonCode Aligner] Update code signature verification

CellProfiler/CellProfiler.download.recipe, CellProfiler/CellProfiler.munki.recipe
Their download link isn't HTTPS but it's hosted on Amazon AWS so I just change it to be HTTPS. ¯\\\_(ツ)\_/¯
```
$ autopkg run CellProfiler.munki -v
Processing CellProfiler.munki...
WARNING: CellProfiler.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher: Found matching text (match): cellprofiler-org.s3.amazonaws.com/CellProfiler.dmg
URLDownloader
URLDownloader: Storing new Last-Modified header: Mon, 18 Apr 2016 14:36:07 GMT
URLDownloader: Storing new ETag header: "a6eecb3cdd547681eedaeb51c7974098"
URLDownloader: Downloaded /Users/itsadmin/Library/AutoPkg/Cache/com.github.n8felton.cellprofiler.munki/downloads/CellProfiler.dmg
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image …
```
=> [CellProfiler] Add download and munki recipes

ParaView/ParaView.download.recipe, ParaView/ParaView.munki.recipe
It could be worse...
```
testmac:~ cwhits$ autopkg run ParaView.munki -v
Processing ParaView.munki...
WARNING: ParaView.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher: Found matching text (folder): v5.4
URLTextSearcher: Found matching text (match): v5.4
URLTextSearcher: Found matching text (match): ParaView-5.4.1-Qt5-OpenGL2-MPI-OSX10.8-64bit.dmg
URLTextSearcher: Found matching text (file): ParaView-5.4.1-Qt5-OpenGL2-MPI-OSX10.8-64bit.dmg
URLDownloader
URLDownloader: Storing new Last-Modified header: Mon, 21 Aug 2017 15:40:44 GMT
URLDownloader: Storing new ETag header: "29c9113-cb8175c-557454d40b700"
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.paraview.munki/down …
```
=> [ParaView] Add download and munki recipes

FirestormViewer/FirestormViewer.munki.recipe
Their app name is dumb but I put in a Jira request for them to fix it.
=> [FirestormViewer] Add munki recipe

MAMP/MAMP.download.recipe
=> MAMP.download

Tidal/Tidal.download.recipe, Tidal/Tidal.munki.recipe
=> [TIDAL] Adding download and munki recipes

PAUP/PAUP.download.recipe
=> [PAUP] Update sparkle feed address

CellProfiler/CellProfiler.download.recipe
=> [CellProfiler] Update code signature

CodonCode/CodonCodeAligner.download.recipe, jGrasp/jGrasp.download.recipe
I tested the modified recipes with `autopkg run --check` but you may want to do the same just to be sure.
=> Update to HTTPS

CodonCode/CodonCodeAligner.download.recipe
=> Updating URLTextSearcher with updated download path

Timeular/Timeular.download.recipe, Timeular/Timeular.install.recipe, Timeular/Timeular.munki.recipe, Timeular/Timeular.pkg.recipe
```
$ autopkg run Timeular.munki                     
Processing Timeular.munki...
WARNING: Timeular.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
The following new items were imported into Munki:
Name      Version  Catalogs  Pkginfo Path                        Pkg Repo Path                     
----      -------  --------  ------------                        -------------                     
Timeular  2.3.5    testing   apps/Timeular/Timeular-2.3.5.plist  apps/Timeular/Timeular-2.3.5.dmg  
```
=> [Timeular] Adding recipes

VMware/VMwareAirWatchAdminAssistant.download.recipe
Joy O. from VMware provided this new feed in #workspaceone on the MacAdmins Slack.
=> Update Sparkle feed

SharedProcessors/YAML.py
The YAML processor is currently failing in AutoPkg version 2.3.1 with the following error:
```
% autopkg run -vvv YamlTest.recipe
Processing YamlTest.recipe...
WARNING: YamlTest.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
Traceback (most recent call last):
File "/usr/local/bin/autopkg", line 2758, in <module>
sys.exit(main(sys.argv))
File "/usr/local/bin/autopkg", line 2754, in main
return subcommands[verb]["function"](argv)
File "/usr/local/bin/autopkg", line 2258, in run_recipes
autopackager.verify(recipe)
File "/Library/AutoPkg/autopkglib/__init__.py", line 789, in verify
variables.update(set(processor_class.output_variables.keys()))
AttributeError: type object 'YAML' has no attribute 'output_variables'
```
The fix is to add an …
=> Add missing attribute output_variables to YAML custom processor

CellProfiler/CellProfiler.download.recipe
```
Paste output here
```
Will add output later
=> Update CellProfiler app name + Certificate

CellProfiler/CellProfiler.download.recipe
Certificate change with the creation of version 4.2.3 of CellProfiler
```
Paste output here
```
=> Update CellProfiler certificate

Amazon/AmazonCorretto.munki.recipe
The recipe currently handles downloading `x86_64` or `arm64` from Amazon, but `supported_architectures` is not set in `pkginfo`.
This proposed change adds a `MUNKI_ARCH` variable to be used in the `supported_architectures` key making override management a bit cleaner and easier. 
```
munkiadmin@ac-munkiadmin-m1 ~ % autopkg run -vvv /Volumes/ac-munki-data/Library/AutoPkg/RecipeOverrides/AmazonCorretto_11_x86_64.munki.recipe
Processing /Volumes/ac-munki-data/Library/AutoPkg/RecipeOverrides/AmazonCorretto_11_x86_64.munki.recipe...
{'ARCH': 'x64',
'AUTOPKG_VERSION': '2.7.2',
'CACHE_DIR': '/Volumes/ac-munki-data/Library/AutoPkg/Cache',
'DOWNLOAD_URL': 'https://corretto.aws/downloads/latest/amazon-corretto-11-x64-macos-jdk.pkg',
'GIT_PATH': '/opt/homebrew/bin/git',
'MAJOR_VERSION': '11', …
```
=> Add munki <key>supported_architectures</key>

Microsoft/MicrosoftEdge.munki.recipe
If you run the current version of the recipe the package ends up with the filename `MicrosoftEdge-118.0.2088.69-118.2088.23102369.pkg`. With the proposed change the filename comes out as `MicrosoftEdge-118.0.2088.69.pkg`.
```
~ % autopkg run -vvvv MicrosoftEdgeTest.munki
Processing MicrosoftEdgeTest.munki...
{'AUTOPKG_VERSION': '2.7.2',
'CHANNEL': '',
'DERIVE_MIN_OS': 'YES',
'FAIL_RECIPES_WITHOUT_TRUST_INFO': True,
'GIT_PATH': '/usr/bin/git',
'MUNKI_CATEGORY': 'Web',
'MUNKI_PKGINFO_FILE_EXTENSION': 'pkginfo',
'MUNKI_REPO': '/Users/macmgmt/repo',
'MUNKI_REPO_SUBDIR': 'software/MicrosoftEdge',
'NAME': 'MicrosoftEdge',
'PARENT_RECIPES': ['/Users/macmgmt/Library/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes/Microsoft/MicrosoftEdge.munki.recipe', …
```
=> Fix duplicate version on imported Munki package

Yubico/yubico-authenticator.download.recipe, Yubico/yubico-authenticator.munki.recipe, Yubico/yubioath-desktop.download.recipe, Yubico/yubioath-desktop.munki.recipe
Replaces yubioath-desktop recipes.
=> Add updated yubico-authenticator recipes
