MegaSoftware/MEGA.munki.recipe, MegaSoftware/README.md
```
$ autopkg run MEGA.munki -v
Processing MEGA.munki...
WARNING: MEGA.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher: Found matching text (version): 7.0.14
URLTextSearcher: Found matching text (build): 7160126
URLTextSearcher: Found matching text (match): 7160126
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.munki.MEGA/downloads/MEGA.dmg
MunkiImporter
MunkiImporter: Copied pkginfo to /munki/pkgsinfo/apps/MEGA/MEGA-7.0.14.plist
MunkiImporter: Copied pkg to /munki/pkgs/apps/MEGA/MEGA-7.0.14.dmg
Receipt written to /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.munki.MEGA/receipts/MEGA-receipt-2016081 …
```
=> Add MEGA.munki recipe

MinitabExpressMU/MinitabExpressMU.munki.recipe, MinitabExpressMU/README.md
Created a Munki recipe for Minitab Express. Using `MT_LICENSE_SERVER` for setting licensing info.
```
$ autopkg run MinitabExpressMU.munki.recipe --key MT_LICENSE_SERVER="27000@license.example.com" -v
Processing MinitabExpressMU.munki.recipe...
WARNING: MinitabExpressMU.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher: Found matching text (url): http://fs1.minitab.com/prodinstalls/minitabexpress/minitabexpress1/1.5.0.0/mac/multi-user/Minitab_Express_MU_v1.5.0.pkg
URLTextSearcher: Found matching text (version): 1.5.0.0
URLTextSearcher: Found matching text (match): http://fs1.minitab.com/prodinstalls/minitabexpress/minitabexpress1/1.5.0.0/mac/multi-user/Minitab_Express_MU_v1.5.0.pkg
URLDownloader
URLDownloader: …
```
=> Add MinitabExpressMU.munki recipe

GraphViz/GraphViz.download.recipe, GraphViz/GraphViz.munki.recipe
Not codesigned.
```
$ pkgutil --check-signature ~/Downloads/graphviz-2.36.0.pkg
Package "graphviz-2.36.0.pkg":
Status: no signature
```
Recipe output:
```
$ autopkg run GraphViz/GraphViz.munki.recipe -v
Processing GraphViz/GraphViz.munki.recipe...
WARNING: GraphViz/GraphViz.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher: Found matching text (match): pub/graphviz/stable/macos/mountainlion/graphviz-2.36.0.pkg
URLDownloader
URLDownloader: Storing new Last-Modified header: Sun, 12 Jan 2014 00:29:04 GMT
URLDownloader: Storing new ETag header: "1c0036-8f8470-4efbb0be01400"
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.munki.GraphViz/downloads/GraphViz.pkg
MunkiImporter …
```
=> Add recipes for GraphViz

Cn3D/Cn3D.download.recipe, Cn3D/Cn3D.munki.recipe
```
$ autopkg run Cn3D.munki.recipe -v
Processing Cn3D.munki.recipe...
WARNING: Cn3D.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher: Found matching text (version): 4.3.1
URLTextSearcher: Found matching text (match): ftp://ftp.ncbi.nlm.nih.gov/cn3d/Cn3D-4.3.1-OSX.zip
URLDownloader
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.munki.Cn3D/downloads/Cn3D-4.3.1-OSX.zip
Unarchiver
Unarchiver: Guessed archive format 'zip' from filename Cn3D-4.3.1-OSX.zip
Unarchiver: Unarchived /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.munki.Cn3D/downloads/Cn3D-4.3.1-OSX.zip to /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.munki.Cn3D/Cn3D
FileFinder …
```
=> Add Cn3D download and munki recipes

OpenRefine/OpenRefine.download.recipe, OpenRefine/OpenRefine.munki.recipe
Added a recipe for OpenRefine.
```
$ autopkg run OpenRefine.munki.recipe -v
Processing OpenRefine.munki.recipe...
WARNING: OpenRefine.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider: Matched regex 'openrefine-mac-.+\.dmg' among asset(s): openrefine-linux-2.7-rc.1.tar.gz, openrefine-mac-2.7-rc.1.dmg, openrefine-win-2.7-rc.1.zip
GitHubReleasesInfoProvider: Selected asset 'openrefine-mac-2.7-rc.1.dmg' from release 'OpenRefine v2.7 Release Candidate 1'
URLDownloader
URLDownloader: Storing new Last-Modified header: Sat, 11 Feb 2017 14:04:05 GMT
URLDownloader: Storing new ETag header: "58c85126b7419a1fca87d6e0941fe8aa"
URLDownloader: Downloaded …
```
=> [OpenRefine] Add munki and download recipe

OpenSC/OpenSC.download.recipe, OpenSC/OpenSC.munki.recipe
```
$ autopkg run -v OpenSC/OpenSC.munki.recipe
Processing OpenSC/OpenSC.munki.recipe...
WARNING: OpenSC/OpenSC.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider: Matched regex 'OpenSC-.+\.dmg' among asset(s): OpenSC-0.16.0-win32_vs12-Light-Release.msi, OpenSC-0.16.0-win32_vs12-Release.msi, OpenSC-0.16.0-win64_vs12-Light-Release.msi, OpenSC-0.16.0-win64_vs12-Release.msi, OpenSC-0.16.0.dmg, opensc-0.16.0.tar.gz
GitHubReleasesInfoProvider: Selected asset 'OpenSC-0.16.0.dmg' from release 'OpenSC 0.16.0'
URLDownloader
URLDownloader: Storing new Last-Modified header: Fri, 03 Jun 2016 13:39:30 GMT
URLDownloader: Storing new ETag header: "47ae3ae2b805c02abc11414143990c0b"
URLDownloader: …
```
=> [OpenSC] add download and munki recipes

NaturalReader/NaturalReaderFree.download.recipe, NaturalReader/NaturalReaderFree.munki.recipe
```
$ autopkg run -v NaturalReaderFree.munki.recipe
Processing NaturalReaderFree.munki.recipe...
WARNING: NaturalReaderFree.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher: Found matching text (version): 14
URLTextSearcher: Found matching text (match): https://s3.amazonaws.com/naturalsoftdownload-voices/software/NaturalReader14Free.pkg
URLDownloader
URLDownloader: Storing new Last-Modified header: Thu, 22 Oct 2015 02:48:14 GMT
URLDownloader: Storing new ETag header: "c1cd738d351e2f6af199980528137ffa"
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.munki.NaturalReaderFree/downloads/NaturalReaderFree.pkg
MunkiPkginfoMerger
MunkiPkginfoMerger: Merged {
version = 14;
} into …
```
=> NaturalReader

KeePassX/KeePassXC.download.recipe, KeePassX/KeePassXC.munki.recipe
```
$ autopkg run KeePassXC.munki.recipe -v
Processing KeePassXC.munki.recipe...
WARNING: KeePassXC.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider: Matched regex 'KeePassXC-.+\.dmg' among asset(s): keepassxc-2.2.0-src.tar.xz, keepassxc-2.2.0-src.tar.xz.DIGEST, keepassxc-2.2.0-src.tar.xz.sig, KeePassXC-2.2.0-Win32-Portable.zip, KeePassXC-2.2.0-Win32-Portable.zip.DIGEST, KeePassXC-2.2.0-Win32-Portable.zip.sig, KeePassXC-2.2.0-Win32.exe, KeePassXC-2.2.0-Win32.exe.DIGEST, KeePassXC-2.2.0-Win32.exe.sig, KeePassXC-2.2.0-Win64-Portable.zip, KeePassXC-2.2.0-Win64-Portable.zip.DIGEST, KeePassXC-2.2.0-Win64-Portable.zip.sig, KeePassXC-2.2.0-Win64.exe, KeePassXC-2.2.0-Win64.exe.DIGEST, …
```
=> [KeePassXC] Add download and munki recipes

SerialCloner/README.md, SerialCloner/SerialCloner.download.recipe, SerialCloner/SerialCloner.munki.recipe
Requires a version of AutoPkg newer than 1.0.1.
```$ autopkg run SerialCloner.munki.recipe -v
Processing SerialCloner.munki.recipe...
WARNING: SerialCloner.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher: Found matching text (match): Serial_Cloner-Download_files/SerialCloner2-6.dmg
URLTextSearcher: Found matching text (foldername): SerialCloner2-6
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.munki.SerialCloner/downloads/SerialCloner.dmg
FileFinder
FileFinder: Mounted disk image /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.munki.SerialCloner/downloads/SerialCloner.dmg
FileFinder: Found file match: …
```
=> [SerialCloner] Add munki and download recipes

ApplePrinterDrivers/AppleEpsonPrinterDrivers.download.recipe
Even though the new page only refers to Lion through Yosemite, SUS is only serving one update, so this must be the one.
=> Update Apple ARTICLE_NUMBER to match new update

KeePassXC/KeePassXC.munki.recipe
Also removed the unattended install bit because you can set that in an override if you really want.
=> Update KeePassXC munki uninstall_method. Fixes #62

Pentaho/DataIntegration.munki.recipe
didn't realize I changed `pathname` to `pkg_path` on my VM without fixing it in git. 😳
=> [Pentaho/DataIntegration] Fixed pkg_path for the munki import

Neo4j/Neo4j-CE.download.recipe, Neo4j/Neo4j-CE.munki.recipe
It was a pain getting the download link because of weird JavaScript and cookie stuff they're doing but I was able to generate it by converting the version number's periods to underscores. 
```
$ autopkg run Neo4j/Neo4j-CE.munki.recipe -v
Processing Neo4j/Neo4j-CE.munki.recipe...
WARNING: Neo4j/Neo4j-CE.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher: Found matching text (version): 3.2.3
URLTextSearcher: Found matching text (match): 3.2.3
com.github.homebysix.FindAndReplace/FindAndReplace
FindAndReplace: Replacing "." with "_" in "3.2.3".
URLDownloader
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.neo4j-ce.munki/downloads/Neo4j-CE.dmg
MunkiImporter …
```
=> [Neo4j] Add community edition munki and download recipes

Yubico/yubioath-desktop.download.recipe
```
autopkg run yubioath-desktop.download.recipe -v
Processing yubioath-desktop.download.recipe...
WARNING: yubioath-desktop.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider: Matched regex '.*pkg$' among asset(s): yubioath-desktop-4.3.0-mac.pkg, yubioath-desktop-4.3.0-mac.pkg.sig, yubioath-desktop-4.3.0-win.exe, yubioath-desktop-4.3.0-win.exe.sig, yubioath-desktop-4.3.0.tar.gz, yubioath-desktop-4.3.0.tar.gz.sig
GitHubReleasesInfoProvider: Selected asset 'yubioath-desktop-4.3.0-mac.pkg' from release 'yubioath-desktop-4.3.0'
URLDownloader
URLDownloader: Storing new Last-Modified header: Mon, 18 Dec 2017 12:20:08 GMT
URLDownloader: Storing new ETag header: …
```
=> [yubioath-desktop] update code signature

Weka/Weka.download.recipe, Weka/Weka.munki.recipe
Fixes #80 
Sample run:
```
$ autopkg run Weka.munki -v
Processing Weka.munki...
WARNING: Weka.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
com.github.n8felton.shared/SourceForgeBestReleaseURLProvider
com.github.n8felton.shared/RemoteFilenameFinder
URLDownloader
URLDownloader: Storing new Last-Modified header: Thu, 21 Dec 2017 21:12:29 GMT
URLDownloader: Storing new ETag header: "76664ba-560e02852a940"
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.n8felton.munki.Weka/downloads/weka-3-8-2-oracle-jvm.dmg
com.github.n8felton.shared/MD5Checksum
MD5Checksum: be546bae7915ca50ca40df7aa1cffae8
MD5Checksum: MD5 Checksum Matches
Copier
Copier: Mounted disk image …
```
=> [Weka] Rename app when it copies

Geneious/Geneious.download.recipe
The download recipe will fail with `URLDownloader: Error: Curl failure: Illegal characters found in URL (exit code 3)` the reason for this appeares to be an end of line character in `GeneiousVersions.txt`. Notice the `\r` in the following output:
```
URLTextSearcher: Found matching text (match): Geneious_mac64_10_2_6_with_jre.dmg
{'Output': {'match': 'Geneious_mac64_10_2_6_with_jre.dmg\r'}}
URLDownloader
{'Input': {'CURL_PATH': '/usr/bin/curl',
'url': u'https://assets.geneious.com/installers/geneious/release/Geneious_mac64_10_2_6_with_jre.dmg\r'}}
```
We avoide this problem by updating the re_pattern to explicitely search for a string ending with `dmg`.
=> Update re_pattern for Geneious

MAMP/MAMP.download.recipe
MAMP has changed their org name, which results in a new cert name to be verified to.
=> Update MAMP.download recipe

BlueJ/BlueJ.download.recipe, BlueJ/BlueJ.install.recipe, BlueJ/BlueJ.munki.recipe, Chimera/Chimera.download.recipe, Cn3D/Cn3D.munki.recipe, Flixel/Cinemagraph Pro.download.recipe, Flixel/Cinemagraph Pro.install.recipe
Because variables can be overridden, it's a good idea to make sure that the recipe will still work even if a non-default variables used. One issue that would prevent recipes from running is using a `NAME` variable in paths that should be hard-coded (e.g. `/Applications/Foo.app`).
This PR removes the `NAME` variable from all file paths and replaces it with the actual app name, which should make the recipe more resilient for overrides.
=> Remove NAME variable from app paths

KeePassXC/KeePassXC.download.recipe
- Update regex search given that since 2.5.2 there is now a 10.12 Sierra specific asset .dmg version on Github that's listed before the 10.13+ .dmg.  Regex simply excludes the `string` Sierra.
- Add ASSET_REGEX input variable so we can choose which version we want to grab
=> Update KeePassXC download recipe for latest Github release

OpenRefine/OpenRefine.download.recipe
These changes should allow users to override the INCLUDE_PRERELEASES variable in their override without changing existing behavior (which is to include pre-releases).
=> Allow users to override INCLUDE_PRERELEASES for OpenRefine

Intel/IntelUnite.munki.recipe
Allow Intel Unite to install the Rogue Amoeba Audio Capture Engine ("ACE") audio plugins upon installation, and remove the plugins (if installed) upon uninstallation.
=> Add support for installing the audio driver

Apache/Maven.download.recipe, Tidal/Tidal.download.recipe
Detected and changed HTTPS URLs automatically using my [HTTPS Spotter](https://www.elliotjordan.com/posts/autopkg-https/) script, and then tested all changed recipes manually to ensure download success.
=> Update all available URLs from HTTP to HTTPS

VMware/VMwareAirWatchAdminAssistant.install.recipe
Simply installs the package from com.github.n8felton.download.VMwareAirWatchAdminAssistant
Very useful for updating AdminAssistant (with embedded munkitools) on an autopkg system
=> Added new VMwareAirWatchAdminAssistant.install recipe

ATTO/ATTODiskBenchmark.pkg.recipe, Catapult/Vision.pkg.recipe, EpicGames/Epic Games Launcher.pkg.recipe, Facebook/Spark AR Studio.pkg.recipe, Microsoft/Microsoft Remote Desktop Beta.pkg.recipe, Timeular/Timeular.pkg.recipe
This pull request removes unused instances of `BUNDLE_ID` from recipe input variables, which will help reduce confusion by new AutoPkg users and simplify overrides created from this point on.
Making `BUNDLE_ID` available as an input variable is a common practice in AutoPkg recipes that use the [PkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-PkgCreator) processor ([example](https://github.com/autopkg/homebysix-recipes/blob/4fec9244a3af0f9b7c8f61f35a5cd7f4622fb162/soma-zone/LaunchControl.pkg.recipe#L40-L41)). It's likely that these recipes transitioned from PkgCreator to the more streamlined [AppPkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-AppPkgCreator) processor some time ago, but the now-unused input variable for `BUNDLE_ID` was never removed.
Recipe run …
=> Remove unused BUNDLE_ID input var

Amazon/AmazonCorretto.download.recipe, Amazon/AmazonCorretto.munki.recipe, Microsoft/MicrosoftEdge.download.recipe
A typo was [found and fixed](https://github.com/autopkg/autopkg/commit/983087f63d49c8dbc4dbbd6bb5ced34321c59ac6) in the template AutoPkg uses when the `autopkg new-recipe` command is used. This PR makes the same change in your recipes that are affected by the typo.
=> Fix MinimumVersion key

Microsoft/MicrosoftEdgeURLProvider.py
Hi, as discussed on macadmins Slack I've changed the linkID URL's so the Universal builds are downloaded instead of the x86_64 builds. I couldn't find any of the Enterprise linkID's, so they'll still download the x86_64 builds. 
For future reference: I found the linkID's by going to [https://www.microsoft.com/en-us/edge](https://www.microsoft.com/en-us/edge) and [https://www.microsoftedgeinsider.com/en-us/download](https://www.microsoftedgeinsider.com/en-us/download) clicking on "Download for macOS" clinking on "Mac with Apple chip" and then checking the "Accept and download" URL with the developer tools(inspect).
Although it says "Mac with Apple chip" these are Universal builds. I've checked the downloads with `file Microsoft\ Edge.app/Contents/MacOS/Microsoft\ Edge` and the output was: …
=> Changed linkID's for Edge URLProvider so Universal builds are downloaded

HPPrinterDrivers/HPPrinterDrivers.download.recipe
Our product number is `J8A10A`, so I believe the current argument value downloads the wrong package. Migrating this to the Input section of the recipe lets users select which driver package to download and manage any changes to `product_number` on their own schedule. I've retained the default product number value.
Closes #82
=> Move HP printer driver product_number to Input

Microsoft/MicrosoftEdgeURLProvider.py, SharedProcessors/SentinelOneInfoProvider.py
As of macOS Monterey 12.3, the version of Python 2 that shipped with macOS located at `/usr/bin/python` [has been removed](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). More context can be found in some posts from Mac admins at the beginning of 2022, aggregated [here](https://scriptingosx.com/2022/03/macos-monterey-12-3-removes-python-2-link-collection/).
Since [version 2.0.2](https://github.com/autopkg/autopkg/releases/tag/v2.0.2), AutoPkg's installer has included its own Python 3 framework, symlinked from `/usr/local/autopkg/python`. This pull request adjusts the "shebang" interpreter paths of processors to replace `/usr/bin/python` with the AutoPkg Python 3 path.
NOTE: Because AutoPkg processors are imported as modules by AutoPkg and not …
=> Update Python path in processors to reflect changes in macOS 12.3+

HPPrinterDrivers/HPPrinterDrivers.download.recipe, SharedProcessors/HPSoftwareInfoProvider.py
Due to some changes on HP's side, the HPPrinterDrivers recipe is not functioning. I have made some changes in order to fix those errors and provide greater flexibility in the recipe.
* Added additional imports
* Removed Python 2 workaround
* Modified HP_BASE_URL to also have a key for the query type
* Added optional query
* Fixed references to case-sensitive environment variables
* Added new HP_QUERY_TYPE environment variable
* Modified "OS" to be `operating_system` to prevent conflicts with `os` built-in.
* Changed "product_number" to "HP_QUERY" as it's ProductNumber sometimes and ModelName otherwise
* Used the packaging versioner to parse the version strings and figure out which is higher. It is *not* always the first one in the new schema.
* Verified if the discovered url begins with …
=> Overhauling HPPrinterDrivers

MAMP/MAMP.download.recipe, MAMP/MAMP.munki.recipe
Hi, @n8felton 
This PR adds in support for downloading architecture specific versions of MAMP. 
I've also updated the Munki recipe so that it creates an Installs Array for the MAMP PRO App, and sets the minimum os version from the Apps info.plist. 
```
autopkg run -v /Users/paul/Documents/GitHub/AutoPkg\ Repos/n8felton-recipes/MAMP/MAMP.munki.recipe 
Processing /Users/paul/Documents/GitHub/AutoPkg Repos/n8felton-recipes/MAMP/MAMP.munki.recipe...
WARNING: /Users/paul/Documents/GitHub/AutoPkg Repos/n8felton-recipes/MAMP/MAMP.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher: Found matching text (filename): MAMP_MAMP_PRO_6.8-M1-arm
URLTextSearcher: Found matching text (version): 6.8
URLTextSearcher: Found matching …
```
=> Update MAMP Recipes with Architecture Support

KeePassXC/KeePassXC.download.recipe, KeePassXC/KeePassXC.munki.recipe
```
{
'ARCH': 'arm64',
'ASSET_REGEX': 'KeePassXC-.*-arm64\\.dmg',
'AUTOPKG_VERSION': '2.7.2',
'FAIL_RECIPES_WITHOUT_TRUST_INFO': True,
'NAME': 'KeePassXC',
'PARENT_RECIPES': [],
'RECIPE_CACHE_DIR': '/Users/mczack/Library/AutoPkg/Cache/com.github.n8felton.download.KeePassXC',
'RECIPE_DIR': '/Users/mczack/Library/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes/KeePassXC',
'RECIPE_OVERRIDE_DIRS': ['Overrides'],
'RECIPE_PATH': '/Users/mczack/Library/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes/KeePassXC/KeePassXC.download.recipe',
'verbose': 4}
{'Input': {'asset_regex': 'KeePassXC-.*-arm64\\.dmg',
'github_repo': 'keepassxreboot/keepassxc',
'include_prereleases': False}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default …
```
=> Add ARCH support for KeePassXC

KeePassXC/KeePassXC.download.recipe
The KeePassXC.download recipe started failing if you use AutoPkg 3.0.0 RC2. Clearly some changes have been made to the `GitHubReleasesInfoProvider` processor that mean regex is handled slightly differently. 
The error is generated by the fact that the processor is downloading a `.dmg.sig` file instead of the `.dmg`:
```
URLDownloader: Downloaded /Users/gpugh/Library/AutoPkg/Cache/com.github.eth-its-recipes.jamf.KeePassXC/downloads/KeePassXC-2.7.6-x86_64.dmg.sig
CodeSignatureVerifier: Error: Error processing path '/Users/gpugh/Library/AutoPkg/Cache/com.github.eth-its-recipes.jamf.KeePassXC/downloads/KeePassXC-2.7.6-x86_64.dmg.sig/KeePassXC.app' with glob
```
This is solved by adding a $ to the end of the regex.
```
GitHubReleasesInfoProvider: Matched regex 'KeePassXC-.*-x86_64\.dmg$' among …
```
=> fix regex issue with KeePassXC download recipe

BlueJ/BlueJ.download.recipe, BlueJ/BlueJ.munki.recipe
Hi, @n8felton 
This PR updates the BlueJ Recipes. 
Download
- Updated regex to search for the DMG file
- Deletion of Unarchiver and  FileFinder steps
- Updated path for Code Signature
- Update path for Versioner
Munki
- Removal of FileFinder and DmgCreator steps
- Updated pkg_path
```
autopkg run -v BlueJ.munki.recipe
Looking for com.github.n8felton.download.BlueJ...
Did not find com.github.n8felton.download.BlueJ in recipe map
Rebuilding recipe map with current working directories...
Looking for com.github.n8felton.download.BlueJ...
Found com.github.n8felton.download.BlueJ in recipe map
**load_recipe time: 0.0052353329956531525
Processing BlueJ.munki.recipe...
WARNING: BlueJ.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding... …
```
=> Update BlueJ Recipes

SentinelOne/SentinelOne.download.recipe, SharedProcessors/SentinelOneInfoProvider.py
```
Processing SentinelOne.download...
{'AUTOPKG_VERSION': '2.7.3',
'DISABLE_CODE_SIGNATURE_VERIFICATION': 'true',
'MUNKI_REPO': '/Users/<SNIP>/CodeProjects/munki/munki-repo',
'NAME': 'SentinelOne',
'PARENT_RECIPES': ['/Users/<SNIP>/Library/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes/SentinelOne/SentinelOne.download.recipe'],
'RECIPE_CACHE_DIR': '/Users/<SNIP>/Library/AutoPkg/Cache/local.download.SentinelOne',
'RECIPE_DIR': '/Users/<SNIP>/CodeProjects/Autopkg/overrides',
'RECIPE_OVERRIDES': '/Users/<SNIP>/CodeProjects/Autopkg/overrides',
'RECIPE_OVERRIDE_DIR': '/Users/<SNIP>/CodeProjects/Autopkg/overrides',
'RECIPE_OVERRIDE_DIRS': ['/Users/<SNIP>/CodeProjects/Autopkg/overrides'],
'RECIPE_PATH': '/Users/<SNIP>/CodeProjects/Autopkg/overrides/SentinelOne.download.recipe', …
```
=> SentinelOne updates

.github/workflows/autopkg_run.yml
As a result of https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
=> Update and pin versions

Intel/IntelUnite.download.recipe
This PR deprecates the Intel Unite recipes, since Intel deprecated the Intel Unite Solution in 2023 ([details](https://www.intel.com/content/www/us/en/download/18371/intel-unite-app.html)).
=> Deprecate Intel Unite recipes

ParaView/ParaView.download.recipe
This PR adjusts the file pattern matched by the ParaView download recipe, and adds an ARCH variable that can be used to specify whether to download the Intel or Apple Silicon version of ParaView.
Verbose recipe run output with default (Intel) architecture:
```
% autopkg run -vvq 'ParaView/ParaView.download.recipe'
Processing ParaView/ParaView.download.recipe...
WARNING: ParaView/ParaView.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'Input': {'re_pattern': '(?P<folder>v\\d\\.\\d+)\\/',
'url': 'https://www.paraview.org/files/?C=N;O=D'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Found matching text (folder): v5.13
URLTextSearcher: Found matching text …
```
=> Fix ParaView recipes and add ARCH input variable

Microsoft/Microsoft Remote Desktop Beta.download.recipe, Microsoft/Microsoft Remote Desktop Beta.install.recipe, Microsoft/Microsoft Remote Desktop Beta.pkg.recipe
This PR updates the name of Microsoft Remote Desktop to [Windows App](https://learn.microsoft.com/en-us/windows-app/overview).
=> Update "Remote Desktop" to "Windows App"

AstroImageJ/AstroImageJ.pkg.recipe, Flixel/Cinemagraph Pro.pkg.recipe, Pentaho/DataIntegration.pkg.recipe
Hundreds of recipes dating from the very beginning of AutoPkg use the `options` key in the `pkg_request` argument of PkgCreator:
```xml
<key>options</key>
<string>purge_ds_store</string>
```
However, this key doesn't serve any purpose at all. The `options` key is ignored and not passed along to `pkgbuild`, regardless of its presence or contents. It appears that this has been the case since the very first public release of AutoPkg 0.1.0!
So this pull request (one of over 100) formally ends this practice and removes the unused and unneeded `options` key from all recipes in the AutoPkg org that use PkgCreator.
Thanks for considering!
_This PR was submitted using [Repo Lasso](https://github.com/homebysix/repo-lasso) v1.2.0._
=> Removal of unused `options` from PkgCreator arguments
